FROM registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.7
LABEL maintainer="YangJian <youken9980@163.com>"

ARG UBUNTU_MIRROR="http://ports.ubuntu.com"

ENV SHELL="/bin/bash"
ENV TZ="Asia/Shanghai"

RUN set -eux && \
    \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" && \
    apt-get install --no-install-recommends -y apt-transport-https ca-certificates tzdata fontconfig locales && \
    mv /usr/share/zoneinfo/Asia/Shanghai /Shanghai && \
    rm -rf /usr/share/zoneinfo && \
    mkdir -p /usr/share/zoneinfo/Asia && \
    mv /Shanghai /usr/share/zoneinfo/Asia/Shanghai && \
    ln -sTf /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/PRC && \
    ln -sTf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    \
    cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i "s|http://ports.ubuntu.com|${UBUNTU_MIRROR}|g" /etc/apt/sources.list && \
    \
    apt-get update && \
    apt install -y ffmpeg && \
    \
    rm -rf /var/lib/apt/lists/* \
           /var/cache/* \
           /tmp/*

WORKDIR /workspace/FunASR/runtime

EXPOSE 10095
STOPSIGNAL SIGTERM

COPY entrypoint-offline.sh /workspace/FunASR/runtime/entrypoint.sh
# ENTRYPOINT ["/workspace/FunASR/runtime/entrypoint.sh"]

# CMD ["bash", "run_server.sh", "--download-model-dir", "/workspace/models", "--model-dir", "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx", "--vad-dir", "damo/speech_fsmn_vad_zh-cn-16k-common-onnx", "--punc-dir", "damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx", "--itn-dir", "thuduj12/fst_itn_zh", "--lm-dir", "damo/speech_ngram_lm_zh-cn-ai-wesp-fst", "--certfile", "0", "--hotword", "/workspace/FunASR/runtime/websocket/hotwords.txt"]
CMD ["/bin/bash"]
