FROM centos:8
LABEL maintainer="YangJian <youken9980@163.com>"

ENV LANG="en_US.UTF-8"
ENV TZ="Asia/Shanghai"

RUN sed -i "/# System wide functions and aliases/a\alias ll='ls -la'" /etc/bashrc && \
    rm -rf /etc/yum.repos.d && mkdir -p /etc/yum.repos.d && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-8.repo && \
    sed -i "s|mirrors.cloud.aliyuncs.com|mirrors.aliyuncs.com|g" /etc/yum.repos.d/CentOS-Base.repo

# yum update -y && \
# rm -rf /etc/yum.repos.d && mkdir -p /etc/yum.repos.d && \
# curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-8.repo && \
# yum clean all && \
# rm -rf /var/cache/yum && \
# yum makecache

# yum update -y
# yum install -y nano which tree wget telnet net-tools traceroute git subversion

STOPSIGNAL SIGTERM

CMD ["/bin/bash"]
