FROM centos:7
LABEL maintainer="YangJian <youken9980@163.com>"

ENV LANG="en_US.UTF-8"
ENV TZ="Asia/Shanghai"

RUN sed -i "/# System wide functions and aliases/a\alias ll='ls -la'" /etc/bashrc && \
    rm -rf /etc/yum.repos.d && mkdir -p /etc/yum.repos.d && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo && \
    sed -i "s|mirrors.cloud.aliyuncs.com|mirrors.aliyuncs.com|g" /etc/yum.repos.d/CentOS-Base.repo

# yum makecache
# yum update -y
# curl -o /etc/yum.repos.d/epel-7.repo http://mirrors.aliyun.com/repo/epel-7.repo && \
# yum install -y epel-release && \
# yum install -y nano which tree wget telnet net-tools traceroute git subversion

STOPSIGNAL SIGTERM

CMD ["/bin/bash"]
