FROM eclipse-temurin:21-jdk-noble
LABEL maintainer="YangJian <youken9980@163.com>"

ARG UBUNTU_MIRROR="http://ports.ubuntu.com"

ENV SHELL="/bin/bash"
ENV TZ="Asia/Shanghai"

RUN set -eux && \
    \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" && \
    apt-get install --no-install-recommends -y apt-transport-https tzdata fontconfig locales axel && \
    mv /usr/share/zoneinfo/Asia/Shanghai /Shanghai && \
    rm -rf /usr/share/zoneinfo && \
    mkdir -p /usr/share/zoneinfo/Asia && \
    mv /Shanghai /usr/share/zoneinfo/Asia/Shanghai && \
    ln -sTf /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/PRC && \
    ln -sTf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    \
    cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak && \
    sed -i "s|http://ports.ubuntu.com|${UBUNTU_MIRROR}|g" /etc/apt/sources.list.d/ubuntu.sources && \
    \
    rm -rf /var/lib/apt/lists/* \
           /var/cache/* \
           /tmp/*
